import React, { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function Kevin(props) {
  const [scale, setScale] = useState([3.5, 3.5, 3.5]);

  useEffect(() => {
    function handleResize() {
      const isMobile = window.innerWidth < 768;
      const base = Math.min(window.innerWidth, window.innerHeight);
      
      // Make Kevin bigger on mobile devices
      if (isMobile) {
        // For mobile: use a larger scale factor and higher minimum
        const s = Math.max(2.5, Math.min(5.0, base / 200));
        setScale([s, s, s]);
      } else {
        // For desktop: keep original logic
        const s = Math.max(0.7, Math.min(3.5, base / 350));
        setScale([s, s, s]);
      }
    }
    window.addEventListener('resize', handleResize);
    handleResize(); // Call once on mount
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const { nodes, materials } = useGLTF('/kevin.glb')
  return (
    <group scale={scale} {...props} dispose={null}>
      <group position={[0, -0.15, -0.068]}>
        <group position={[0, 0.066, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part.geometry}
            material={materials['white medium gloss plastic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_10.geometry}
            material={materials['color-8']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_100.geometry}
            material={materials['color-135']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_101.geometry}
            material={materials['color-137']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_102.geometry}
            material={materials['color-146']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_103.geometry}
            material={materials['PW-MT11030-2']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_104.geometry}
            material={materials['PW-MT11030-3']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_105.geometry}
            material={materials['PW-MT11030-4']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_106.geometry}
            material={materials['satin finish stainless steel-2']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_107.geometry}
            material={materials['satin finish stainless steel-4']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_108.geometry}
            material={materials['PW-MT11030-5']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_109.geometry}
            material={materials['PW-MT11030-6']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_11.geometry}
            material={materials['color-10']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_110.geometry}
            material={materials['PW-MT11030-7']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_111.geometry}
            material={materials['satin finish aluminum']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_112.geometry}
            material={materials['color-155 (Cosmetic Thread)']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_113.geometry}
            material={materials['satin finish stainless steel-6']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_114.geometry}
            material={materials['pw-mt11030']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_115.geometry}
            material={materials['PW-MT11030-8']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_116.geometry}
            material={materials['PW-MT11030-11']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_117.geometry}
            material={materials['color-165']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_118.geometry}
            material={materials['color-170']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_12.geometry}
            material={materials['White-PW-MT11050']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_13.geometry}
            material={materials['color-12']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_14.geometry}
            material={materials['polished aluminum']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_15.geometry}
            material={materials.acrylic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_16.geometry}
            material={materials['color-17']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_17.geometry}
            material={materials['color-18']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_18.geometry}
            material={materials['color-19']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_19.geometry}
            material={materials['color-20']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_2.geometry}
            material={materials['black medium gloss plastic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_20.geometry}
            material={materials['color-21']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_21.geometry}
            material={materials['color-22']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_22.geometry}
            material={materials['color-23']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_23.geometry}
            material={materials['color-24']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_24.geometry}
            material={materials['color-25']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_25.geometry}
            material={materials['color-27']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_26.geometry}
            material={materials['color-28']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_27.geometry}
            material={materials['color-29']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_28.geometry}
            material={materials['color-30']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_29.geometry}
            material={materials['color-31']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_3.geometry}
            material={materials['black low gloss plastic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_30.geometry}
            material={materials['color-33']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_31.geometry}
            material={materials['color-34']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_32.geometry}
            material={materials['color-35']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_33.geometry}
            material={materials['color-36']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_34.geometry}
            material={materials['color-37']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_35.geometry}
            material={materials['color-49']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_36.geometry}
            material={materials['color-50']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_37.geometry}
            material={materials['color-53']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_38.geometry}
            material={materials['color-54']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_39.geometry}
            material={materials['color-55']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_4.geometry}
            material={materials.color}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_40.geometry}
            material={materials['color-56']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_41.geometry}
            material={materials['color-58']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_42.geometry}
            material={materials['PW-MT11030']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_43.geometry}
            material={materials['dark grey medium gloss plastic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_44.geometry}
            material={materials['color-60']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_45.geometry}
            material={materials['color-62']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_46.geometry}
            material={materials['color-64']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_47.geometry}
            material={materials['color-65']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_48.geometry}
            material={materials['color-67']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_49.geometry}
            material={materials['color-70']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_5.geometry}
            material={materials['polished steel']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_50.geometry}
            material={materials['color-74']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_51.geometry}
            material={materials['color-77']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_52.geometry}
            material={materials['color-78']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_53.geometry}
            material={materials['color-79']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_54.geometry}
            material={materials['color-81']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_55.geometry}
            material={materials['color-82']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_56.geometry}
            material={materials['color-83']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_57.geometry}
            material={materials['color-84']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_58.geometry}
            material={materials['color-85']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_59.geometry}
            material={materials['color-86']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_6.geometry}
            material={materials['color-2']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_60.geometry}
            material={materials['color-87']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_61.geometry}
            material={materials['color-88']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_62.geometry}
            material={materials['color-89']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_63.geometry}
            material={materials['color-90']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_64.geometry}
            material={materials['color-91']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_65.geometry}
            material={materials['color-92']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_66.geometry}
            material={materials['color-93']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_67.geometry}
            material={materials['color-94']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_68.geometry}
            material={materials['color-95']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_69.geometry}
            material={materials['color-96']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_7.geometry}
            material={materials['satin finish stainless steel']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_70.geometry}
            material={materials['color-97']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_71.geometry}
            material={materials['color-98']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_72.geometry}
            material={materials['color-99']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_73.geometry}
            material={materials['color-100']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_74.geometry}
            material={materials['color-102']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_75.geometry}
            material={materials['color-103']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_76.geometry}
            material={materials['color-104']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_77.geometry}
            material={materials['color-105']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_78.geometry}
            material={materials['color-106']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_79.geometry}
            material={materials['color-107']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_8.geometry}
            material={materials['color-3']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_80.geometry}
            material={materials['color-108']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_81.geometry}
            material={materials['color-111']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_82.geometry}
            material={materials['color-112']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_83.geometry}
            material={materials['color-114']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_84.geometry}
            material={materials['yellow low gloss plastic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_85.geometry}
            material={materials['dark grey low gloss plastic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_86.geometry}
            material={materials['blue low gloss plastic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_87.geometry}
            material={materials['red low gloss plastic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_88.geometry}
            material={materials['green low gloss plastic']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_89.geometry}
            material={materials['blue low gloss plastic-2']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_9.geometry}
            material={materials['color-5']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_90.geometry}
            material={materials['color-119']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_91.geometry}
            material={materials['color-120']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_92.geometry}
            material={materials['color-121']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_93.geometry}
            material={materials['color-122']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_94.geometry}
            material={materials['color-123']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_95.geometry}
            material={materials['color-128']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_96.geometry}
            material={materials['color-130']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_97.geometry}
            material={materials['color-131']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_98.geometry}
            material={materials['color-132']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Part_99.geometry}
            material={materials['color-134']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/kevin.glb')



